apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  namespace: {{ .Values.namespace.name }}
  name: techtrends
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: techtrends
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
        - containerPort: 
          protocol: {{ .Values.service.protocol }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.service.targetPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.service.targetPort }}